/* AUTO-GENERATED by fetch-data.js on 2026-09-30T09:31:21.413Z
   Source: API-Football (api-sports.io). Do not edit by hand — re-run the
   script to refresh. Each team att/def rating is normalised so 1.0 = league
   average, exactly as window.DATA expects. */
window.DATA = {
  "leagueAvgGoals": 2.7,
  "homeAdvantage": 1.15,
  "teams": {
    "Liverpool": {
      "att": 1.67,
      "def": 0.8,
      "league": "Premier League"
    },
    "Arsenal": {
      "att": 1.34,
      "def": 0.66,
      "league": "Premier League"
    },
    "Man City": {
      "att": 1.4,
      "def": 0.86,
      "league": "Premier League"
    },
    "Chelsea": {
      "att": 1.25,
      "def": 0.84,
      "league": "Premier League"
    },
    "Newcastle": {
      "att": 1.32,
      "def": 0.91,
      "league": "Premier League"
    },
    "Aston Villa": {
      "att": 1.13,
      "def": 0.99,
      "league": "Premier League"
    },
    "Nottingham Forest": {
      "att": 1.13,
      "def": 0.9,
      "league": "Premier League"
    },
    "Brighton": {
      "att": 1.28,
      "def": 1.15,
      "league": "Premier League"
    },
    "Bournemouth": {
      "att": 1.13,
      "def": 0.9,
      "league": "Premier League"
    },
    "Brentford": {
      "att": 1.28,
      "def": 1.11,
      "league": "Premier League"
    },
    "Fulham": {
      "att": 1.05,
      "def": 1.05,
      "league": "Premier League"
    },
    "Crystal Palace": {
      "att": 0.99,
      "def": 0.99,
      "league": "Premier League"
    },
    "Everton": {
      "att": 0.82,
      "def": 0.86,
      "league": "Premier League"
    },
    "West Ham": {
      "att": 0.9,
      "def": 1.21,
      "league": "Premier League"
    },
    "Man United": {
      "att": 0.86,
      "def": 1.05,
      "league": "Premier League"
    },
    "Wolves": {
      "att": 1.05,
      "def": 1.34,
      "league": "Premier League"
    },
    "Tottenham": {
      "att": 1.25,
      "def": 1.27,
      "league": "Premier League"
    },
    "Leicester": {
      "att": 0.64,
      "def": 1.56,
      "league": "Premier League"
    },
    "Ipswich": {
      "att": 0.7,
      "def": 1.6,
      "league": "Premier League"
    },
    "Southampton": {
      "att": 0.51,
      "def": 1.67,
      "league": "Premier League"
    },
    "Barcelona": {
      "att": 1.99,
      "def": 0.76,
      "league": "La Liga"
    },
    "Real Madrid": {
      "att": 1.52,
      "def": 0.74,
      "league": "La Liga"
    },
    "Atletico": {
      "att": 1.32,
      "def": 0.58,
      "league": "La Liga"
    },
    "Athletic": {
      "att": 1.05,
      "def": 0.56,
      "league": "La Liga"
    },
    "Villarreal": {
      "att": 1.38,
      "def": 0.99,
      "league": "La Liga"
    },
    "Real Betis": {
      "att": 1.11,
      "def": 0.97,
      "league": "La Liga"
    },
    "Celta Vigo": {
      "att": 1.15,
      "def": 1.11,
      "league": "La Liga"
    },
    "Rayo Vallecano": {
      "att": 0.8,
      "def": 0.88,
      "league": "La Liga"
    },
    "Osasuna": {
      "att": 0.93,
      "def": 1.01,
      "league": "La Liga"
    },
    "Mallorca": {
      "att": 0.68,
      "def": 0.86,
      "league": "La Liga"
    },
    "Sociedad": {
      "att": 0.68,
      "def": 0.9,
      "league": "La Liga"
    },
    "Valencia": {
      "att": 0.86,
      "def": 1.05,
      "league": "La Liga"
    },
    "Getafe": {
      "att": 0.66,
      "def": 0.76,
      "league": "La Liga"
    },
    "Espanyol": {
      "att": 0.78,
      "def": 0.99,
      "league": "La Liga"
    },
    "Alaves": {
      "att": 0.74,
      "def": 0.93,
      "league": "La Liga"
    },
    "Girona": {
      "att": 0.86,
      "def": 1.17,
      "league": "La Liga"
    },
    "Sevilla": {
      "att": 0.82,
      "def": 1.07,
      "league": "La Liga"
    },
    "Leganes": {
      "att": 0.76,
      "def": 1.09,
      "league": "La Liga"
    },
    "Las Palmas": {
      "att": 0.78,
      "def": 1.19,
      "league": "La Liga"
    },
    "Valladolid": {
      "att": 0.51,
      "def": 1.75,
      "league": "La Liga"
    },
    "Napoli": {
      "att": 1.15,
      "def": 0.53,
      "league": "Serie A"
    },
    "Inter": {
      "att": 1.54,
      "def": 0.68,
      "league": "Serie A"
    },
    "Atalanta": {
      "att": 1.52,
      "def": 0.72,
      "league": "Serie A"
    },
    "Juventus": {
      "att": 1.13,
      "def": 0.68,
      "league": "Serie A"
    },
    "Roma": {
      "att": 1.09,
      "def": 0.68,
      "league": "Serie A"
    },
    "Fiorentina": {
      "att": 1.17,
      "def": 0.8,
      "league": "Serie A"
    },
    "Lazio": {
      "att": 1.19,
      "def": 0.95,
      "league": "Serie A"
    },
    "Milan": {
      "att": 1.19,
      "def": 0.84,
      "league": "Serie A"
    },
    "Bologna": {
      "att": 1.11,
      "def": 0.91,
      "league": "Serie A"
    },
    "Como": {
      "att": 0.95,
      "def": 1.01,
      "league": "Serie A"
    },
    "Torino": {
      "att": 0.76,
      "def": 0.88,
      "league": "Serie A"
    },
    "Udinese": {
      "att": 0.8,
      "def": 1.09,
      "league": "Serie A"
    },
    "Genoa": {
      "att": 0.72,
      "def": 0.95,
      "league": "Serie A"
    },
    "Verona": {
      "att": 0.66,
      "def": 1.28,
      "league": "Serie A"
    },
    "Cagliari": {
      "att": 0.78,
      "def": 1.09,
      "league": "Serie A"
    },
    "Parma": {
      "att": 0.86,
      "def": 1.13,
      "league": "Serie A"
    },
    "Lecce": {
      "att": 0.53,
      "def": 1.13,
      "league": "Serie A"
    },
    "Empoli": {
      "att": 0.64,
      "def": 1.15,
      "league": "Serie A"
    },
    "Venezia": {
      "att": 0.62,
      "def": 1.09,
      "league": "Serie A"
    },
    "Monza": {
      "att": 0.54,
      "def": 1.34,
      "league": "Serie A"
    }
  },
  "fixtures": [],
  "history": [],
  "popularLeagues": [
    {
      "name": "UEFA Champions League",
      "icon": "⚽"
    },
    {
      "name": "UEFA Europa League",
      "icon": "🏆"
    },
    {
      "name": "Premier League",
      "icon": "🏴"
    },
    {
      "name": "La Liga",
      "icon": "🇪🇸"
    },
    {
      "name": "Bundesliga",
      "icon": "🇩🇪"
    },
    {
      "name": "Serie A",
      "icon": "🇮🇹"
    },
    {
      "name": "Ligue 1",
      "icon": "🇫🇷"
    },
    {
      "name": "Eredivisie",
      "icon": "🇳🇱"
    },
    {
      "name": "Liga Portugal",
      "icon": "🇵🇹"
    },
    {
      "name": "Brasileiro Serie A",
      "icon": "🇧🇷"
    },
    {
      "name": "Scottish Premiership",
      "icon": "🏴"
    },
    {
      "name": "Süper Lig",
      "icon": "🇹🇷"
    },
    {
      "name": "Saudi Pro League",
      "icon": "🇸🇦"
    }
  ],
  "countries": [
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Belgium",
    "Brazil",
    "Bulgaria",
    "Chile",
    "China",
    "Colombia",
    "Croatia",
    "Denmark",
    "England",
    "France",
    "Germany",
    "Greece",
    "Italy",
    "Japan",
    "Mexico",
    "Netherlands",
    "Norway",
    "Poland",
    "Portugal",
    "Saudi Arabia",
    "Scotland",
    "Spain",
    "Sweden",
    "Switzerland",
    "Turkey",
    "USA"
  ]
};
